name = "tastoids"
version = "1.1.1"
description = "Tastoids are a uniform abstraction of 'taste' and Algebra thereof."
licences = ["AGPL-3.0-only"]
 
repository = { type = "github", user = "avescodes", repo = "tastoids.gleam" }

# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.5.1 and < 2.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"
